In [15]:
import os
import numpy as np
import torchani
from torchani.data._pyanitools import anidataloader
from torchani.data._pyanitools import datapacker

In [2]:
db = anidataloader('./COMP6/COMP6v1/DrugBank/drugbank_testset.h5')
mol_data = dict()
n_mol = 0
for i, data in enumerate(db):
    # print(data['path'])
    # print(data.keys())
    n_mol += 1
    mol_data[str(n_mol)] = data
    if i == 1:
        # print(data['species'])
        # print(data['energies'])
        # print(data['cm5'])
        mol = data['species']
        unique, counts = np.unique(mol, return_counts=True)
        print(unique, counts)

['C' 'H' 'N' 'O'] [6 9 3 2]


In [3]:
# print(mol_data['1'])
print(len(mol_data['1']['species']))
print(mol_data['1']['coordinates'].shape)
print(mol_data['1']['energies'].shape)
print(mol_data['1']['cm5'].shape)
print(mol_data['1']['forces'].shape)
print(mol_data['1']['hirdipole'].shape)
print(mol_data['1']['hirshfeld'].shape)
print(mol_data['1']['spindensities'].shape)
sidx = np.arange(55)
print(sidx)
print(mol_data['1']['cm5'][:, 55])
print(mol_data['1']['hirdipole'][:, 55, :])

55
(16, 55, 3)
(16,)
(16, 56)
(16, 55, 3)
(16, 56, 3)
(16, 56)
(16, 56)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54]
[-9.80e-05  1.31e-04  1.14e-04  5.70e-05 -8.40e-05 -1.58e-04  2.40e-05
 -3.10e-05  2.01e-04  8.20e-05  1.92e-04 -2.09e-04 -4.80e-05 -2.73e-04
  2.09e-04 -1.55e-04]
[[ 0.175684 -0.603649  0.145825]
 [ 0.225839 -0.494023  0.15007 ]
 [ 0.136876 -0.464298 -0.077373]
 [-0.052363 -0.554418  0.407979]
 [ 0.096371 -0.449918 -0.095525]
 [ 0.146794 -0.406735  0.086259]
 [ 0.125541 -0.450917 -0.072203]
 [-0.06494  -0.365422 -0.210527]
 [ 0.215297 -0.42299   0.035845]
 [ 0.40227  -0.747785  0.166399]
 [ 0.385566 -0.596758 -0.238421]
 [-0.044056 -0.771979  0.07404 ]
 [ 0.134514 -0.428615 -0.062024]
 [ 0.061367 -0.51086   0.121787]
 [-0.301717 -0.544614 -0.111458]
 [ 0.234535 -0.468636 -0.03536 ]]


In [4]:
dpack = datapacker('./COMP6/COMP6v1/DrugBank/drugbank_testset_mod2.h5')

for k, data in mol_data.items():
    Na = len(data['species'])
    data_mod = {'species': data['species'],
                'coordinates': data['coordinates'],
                'energies': data['energies'],
                'forces': data['forces'],
                'cm5': data['cm5'][:, 0:Na],
                'cm5_total': data['cm5'][:, Na],
                'hirshfeld': data['hirshfeld'][:, 0:Na],
                'hirshfeld_total': data['hirshfeld'][:, Na],
                'hirdipole': data['hirdipole'][:, 0:Na, :],
                'dipole': data['hirdipole'][:, Na, :]
                }

    dpack.store_data(data['path'],
                     species = data_mod['species'],
                     coordinates = data_mod['coordinates'],
                     energies = data_mod['energies'],
                     forces = data_mod['forces'],
                     cm5 = data_mod['cm5'],
                     cm5_total = data_mod['cm5_total'],
                     hirshfeld = data_mod['hirshfeld'],
                     hirshfeld_total = data_mod['hirshfeld_total'],
                     hirdipole = data_mod['hirdipole'],
                     dipole = data_mod['dipole']
                    )        
dpack.cleanup()

In [5]:
for data in anidataloader('./COMP6/COMP6v1/DrugBank/drugbank_testset_mod2.h5'):
    print(data['path'])
    print(data.keys())
    print(len(data['species']))
    print(data['coordinates'].shape)
    print(data['energies'].shape)
    print(data['forces'].shape)
    print(data['cm5'].shape)
    print(data['cm5_total'].shape)
    print(data['hirshfeld'].shape)
    print(data['hirshfeld_total'].shape)
    print(data['hirdipole'].shape)
    print(data['dipole'].shape)
    break


/drugbank/mol0000
dict_keys(['path', 'cm5', 'cm5_total', 'coordinates', 'dipole', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'hirshfeld_total', 'species'])
55
(16, 55, 3)
(16,)
(16, 55, 3)
(16, 55)
(16,)
(16, 55)
(16,)
(16, 55, 3)
(16, 3)


In [45]:
db = anidataloader('../GDB07to09/gdb11_07_test500.h5')
mol_data = dict()
n_mol = 0
for i, data in enumerate(db):
    print(data['path'])
    print(data.keys())
    n_mol += 1
    mol_data[str(n_mol)] = data
    if i == 1:
        print(data['species'])
        # print(data['energies'])
        # print(data['cm5'])
        mol = data['species']
        unique, counts = np.unique(mol, return_counts=True)
        print(unique, counts)

dpack = datapacker('gdb11_07_test500_mod.h5')
for k, data in mol_data.items():
    Na = len(data['species'])
    data_mod = {'species': data['species'],
                'coordinates': data['coordinates'],
                'energies': data['energies'],
                'forces': data['forces'],
                'cm5': data['cm5'][:, 0:Na],
                'cm5_total': data['cm5'][:, Na],
                'hirshfeld': data['hirshfeld'][:, 0:Na],
                'hirshfeld_total': data['hirshfeld'][:, Na]
                }

    dpack.store_data(data['path'],
                     species = data_mod['species'],
                     coordinates = data_mod['coordinates'],
                     energies = data_mod['energies'],
                     forces = data_mod['forces'],
                     cm5 = data_mod['cm5'],
                     cm5_total = data_mod['cm5_total'],
                     hirshfeld = data_mod['hirshfeld'],
                     hirshfeld_total = data_mod['hirshfeld_total'],
                    )        
dpack.cleanup()

/gdb11_s07/mol0000
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0001
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
['N', 'C', 'C', 'C', 'C', 'O', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
['C' 'H' 'N' 'O'] [ 5 11  1  1]
/gdb11_s07/mol0002
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0003
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0004
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0005
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mo

/gdb11_s07/mol0065
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0066
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0067
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0068
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0069
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0070
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0071
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensi

/gdb11_s07/mol0134
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0135
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0136
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0137
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0138
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0139
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0140
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensi

dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0200
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0201
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0202
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0203
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0204
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0205
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/

/gdb11_s07/mol0265
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0266
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0267
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0268
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0269
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0270
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0271
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensi

/gdb11_s07/mol0328
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0329
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0330
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0331
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0332
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0333
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0334
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensi

/gdb11_s07/mol0413
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0414
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0415
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0416
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0417
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0418
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0419
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensi

/gdb11_s07/mol0470
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0471
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0472
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0473
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0474
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0475
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensities'])
/gdb11_s07/mol0476
dict_keys(['path', 'cm5', 'coordinates', 'energies', 'forces', 'hirdipole', 'hirshfeld', 'lot', 'species', 'spindensi

In [46]:
db = anidataloader('../GDB07to09/gdb11_08_test500.h5')
mol_data = dict()
n_mol = 0
for i, data in enumerate(db):
    # print(data['path'])
    # print(data.keys())
    n_mol += 1
    mol_data[str(n_mol)] = data
    if i == 1:
        print(data['species'])
        # print(data['energies'])
        # print(data['cm5'])
        mol = data['species']
        unique, counts = np.unique(mol, return_counts=True)
        print(unique, counts)

dpack = datapacker('gdb11_08_test500_mod.h5')
for k, data in mol_data.items():
    Na = len(data['species'])
    data_mod = {'species': data['species'],
                'coordinates': data['coordinates'],
                'energies': data['energies'],
                'forces': data['forces'],
                'cm5': data['cm5'][:, 0:Na],
                'cm5_total': data['cm5'][:, Na],
                'hirshfeld': data['hirshfeld'][:, 0:Na],
                'hirshfeld_total': data['hirshfeld'][:, Na]
                }

    dpack.store_data(data['path'],
                     species = data_mod['species'],
                     coordinates = data_mod['coordinates'],
                     energies = data_mod['energies'],
                     forces = data_mod['forces'],
                     cm5 = data_mod['cm5'],
                     cm5_total = data_mod['cm5_total'],
                     hirshfeld = data_mod['hirshfeld'],
                     hirshfeld_total = data_mod['hirshfeld_total'],
                    )        
dpack.cleanup()

['C', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
['C' 'H' 'N' 'O'] [ 6 13  1  1]


In [47]:
db = anidataloader('../GDB07to09/gdb11_09_test500.h5')
mol_data = dict()
n_mol = 0
for i, data in enumerate(db):
    # print(data['path'])
    # print(data.keys())
    n_mol += 1
    mol_data[str(n_mol)] = data
    if i == 1:
        print(data['species'])
        # print(data['energies'])
        # print(data['cm5'])
        mol = data['species']
        unique, counts = np.unique(mol, return_counts=True)
        print(unique, counts)

dpack = datapacker('gdb11_09_test500_mod.h5')
for k, data in mol_data.items():
    Na = len(data['species'])
    data_mod = {'species': data['species'],
                'coordinates': data['coordinates'],
                'energies': data['energies'],
                'forces': data['forces'],
                'cm5': data['cm5'][:, 0:Na],
                'cm5_total': data['cm5'][:, Na],
                'hirshfeld': data['hirshfeld'][:, 0:Na],
                'hirshfeld_total': data['hirshfeld'][:, Na]
                }

    dpack.store_data(data['path'],
                     species = data_mod['species'],
                     coordinates = data_mod['coordinates'],
                     energies = data_mod['energies'],
                     forces = data_mod['forces'],
                     cm5 = data_mod['cm5'],
                     cm5_total = data_mod['cm5_total'],
                     hirshfeld = data_mod['hirshfeld'],
                     hirshfeld_total = data_mod['hirshfeld_total'],
                    )        
dpack.cleanup()

['C', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
['C' 'H' 'N' 'O'] [ 7 13  1  1]


In [48]:
db = anidataloader('../GDB10to13/gdb11_10_test500.h5')
mol_data = dict()
n_mol = 0
for i, data in enumerate(db):
    # print(data['path'])
    # print(data.keys())
    n_mol += 1
    mol_data[str(n_mol)] = data
    if i == 1:
        print(data['species'])
        # print(data['energies'])
        # print(data['cm5'])
        mol = data['species']
        unique, counts = np.unique(mol, return_counts=True)
        print(unique, counts)

dpack = datapacker('gdb11_10_test500_mod.h5')
for k, data in mol_data.items():
    Na = len(data['species'])
    data_mod = {'species': data['species'],
                'coordinates': data['coordinates'],
                'energies': data['energies'],
                'forces': data['forces'],
                'cm5': data['cm5'][:, 0:Na],
                'cm5_total': data['cm5'][:, Na],
                'hirshfeld': data['hirshfeld'][:, 0:Na],
                'hirshfeld_total': data['hirshfeld'][:, Na]
                }

    dpack.store_data(data['path'],
                     species = data_mod['species'],
                     coordinates = data_mod['coordinates'],
                     energies = data_mod['energies'],
                     forces = data_mod['forces'],
                     cm5 = data_mod['cm5'],
                     cm5_total = data_mod['cm5_total'],
                     hirshfeld = data_mod['hirshfeld'],
                     hirshfeld_total = data_mod['hirshfeld_total'],
                    )        
dpack.cleanup()

['C', 'C', 'C', 'C', 'C', 'N', 'C', 'N', 'O', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
['C' 'H' 'N' 'O'] [ 7 12  2  1]


In [49]:
db = anidataloader('../GDB10to13/gdb11_11_test500.h5')
mol_data = dict()
n_mol = 0
for i, data in enumerate(db):
    # print(data['path'])
    # print(data.keys())
    n_mol += 1
    mol_data[str(n_mol)] = data
    if i == 1:
        print(data['species'])
        # print(data['energies'])
        # print(data['cm5'])
        mol = data['species']
        unique, counts = np.unique(mol, return_counts=True)
        print(unique, counts)

dpack = datapacker('gdb11_11_test500_mod.h5')
for k, data in mol_data.items():
    Na = len(data['species'])
    data_mod = {'species': data['species'],
                'coordinates': data['coordinates'],
                'energies': data['energies'],
                'forces': data['forces'],
                'cm5': data['cm5'][:, 0:Na],
                'cm5_total': data['cm5'][:, Na],
                'hirshfeld': data['hirshfeld'][:, 0:Na],
                'hirshfeld_total': data['hirshfeld'][:, Na]
                }

    dpack.store_data(data['path'],
                     species = data_mod['species'],
                     coordinates = data_mod['coordinates'],
                     energies = data_mod['energies'],
                     forces = data_mod['forces'],
                     cm5 = data_mod['cm5'],
                     cm5_total = data_mod['cm5_total'],
                     hirshfeld = data_mod['hirshfeld'],
                     hirshfeld_total = data_mod['hirshfeld_total'],
                    )        
dpack.cleanup()

['O', 'C', 'C', 'C', 'C', 'C', 'O', 'C', 'C', 'C', 'N', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
['C' 'H' 'N' 'O'] [8 9 1 2]


In [50]:
db = anidataloader('../GDB10to13/gdb13_12_test1000.h5')
mol_data = dict()
n_mol = 0
for i, data in enumerate(db):
    # print(data['path'])
    # print(data.keys())
    n_mol += 1
    mol_data[str(n_mol)] = data
    if i == 1:
        print(data['species'])
        # print(data['energies'])
        # print(data['cm5'])
        mol = data['species']
        unique, counts = np.unique(mol, return_counts=True)
        print(unique, counts)

dpack = datapacker('gdb13_12_test1000_mod.h5')
for k, data in mol_data.items():
    Na = len(data['species'])
    data_mod = {'species': data['species'],
                'coordinates': data['coordinates'],
                'energies': data['energies'],
                'forces': data['forces'],
                'cm5': data['cm5'][:, 0:Na],
                'cm5_total': data['cm5'][:, Na],
                'hirshfeld': data['hirshfeld'][:, 0:Na],
                'hirshfeld_total': data['hirshfeld'][:, Na]
                }

    dpack.store_data(data['path'],
                     species = data_mod['species'],
                     coordinates = data_mod['coordinates'],
                     energies = data_mod['energies'],
                     forces = data_mod['forces'],
                     cm5 = data_mod['cm5'],
                     cm5_total = data_mod['cm5_total'],
                     hirshfeld = data_mod['hirshfeld'],
                     hirshfeld_total = data_mod['hirshfeld_total'],
                    )        
dpack.cleanup()

['C', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'N', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
['C' 'H' 'N'] [ 9 15  3]


In [51]:
db = anidataloader('../GDB10to13/gdb13_13_test1000.h5')
mol_data = dict()
n_mol = 0
for i, data in enumerate(db):
    # print(data['path'])
    # print(data.keys())
    n_mol += 1
    mol_data[str(n_mol)] = data
    if i == 1:
        print(data['species'])
        # print(data['energies'])
        # print(data['cm5'])
        mol = data['species']
        unique, counts = np.unique(mol, return_counts=True)
        print(unique, counts)

dpack = datapacker('gdb13_13_test1000_mod.h5')
for k, data in mol_data.items():
    Na = len(data['species'])
    data_mod = {'species': data['species'],
                'coordinates': data['coordinates'],
                'energies': data['energies'],
                'forces': data['forces'],
                'cm5': data['cm5'][:, 0:Na],
                'cm5_total': data['cm5'][:, Na],
                'hirshfeld': data['hirshfeld'][:, 0:Na],
                'hirshfeld_total': data['hirshfeld'][:, Na]
                }

    dpack.store_data(data['path'],
                     species = data_mod['species'],
                     coordinates = data_mod['coordinates'],
                     energies = data_mod['energies'],
                     forces = data_mod['forces'],
                     cm5 = data_mod['cm5'],
                     cm5_total = data_mod['cm5_total'],
                     hirshfeld = data_mod['hirshfeld'],
                     hirshfeld_total = data_mod['hirshfeld_total'],
                    )        
dpack.cleanup()

['C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
['C' 'H' 'N' 'O'] [11 15  1  1]


In [13]:
import os
import numpy as np
import torchani
from torchani.data._pyanitools import anidataloader
from torchani.data._pyanitools import datapacker

count = 0
for data in anidataloader('./COMP6/COMP6v1/DrugBank/drugbank_testset.h5'):
    count += 1
    filename = data['path'].split('/')[-1] + '.xyz'
    f_out = open(filename, 'w+')
    for i in range(len(data['coordinates'])):
        f_out.write('%d \n' % len(data['species']))
        f_out.write(' mol: %s conformer: %d \n' % (filename, i+1))
        for at, coords in zip(data['species'], data['coordinates'][i]):
            f_out.write('%-5s %10.5f %10.5f %10.5f\n' % (at, coords[0], coords[1], coords[2]))
    f_out.close()
    if count > 10:
        break


In [14]:
import os
import numpy as np
import torchani
from torchani.data._pyanitools import anidataloader
from torchani.data._pyanitools import datapacker

count = 0
for data in anidataloader('./ani-1x/ani_al-9.0.1.h5'):
    count += 1
    filename = 'ani_901_' + data['path'].split('/')[-1] + '.xyz'
    f_out = open(filename, 'w+')
    for i in range(len(data['coordinates'])):
        f_out.write('%d \n' % len(data['species']))
        f_out.write(' mol: %s conformer: %d \n' % (filename, i+1))
        for at, coords in zip(data['species'], data['coordinates'][i]):
            f_out.write('%-5s %10.5f %10.5f %10.5f\n' % (at, coords[0], coords[1], coords[2]))
    f_out.close()
    if count > 10:
        break


In [21]:
import os
import numpy as np
import torchani
from torchani.data._pyanitools import anidataloader
from torchani.data._pyanitools import datapacker

mol_data = dict()
n_mol = 0
db = anidataloader('./ani1x-20191001_rz.h5')
dpack1 = datapacker('./ani1x-20191001_wb97x_dz_dipole.h5')
dpack2 = datapacker('./ani1x-20191001_wb97x_tz_dipole.h5')
dpack3 = datapacker('./ani1x-20191001_ccsdt_cbs.h5')

for i, data in enumerate(db):
    # print(data['path'])
    # print(data.keys())
    n_mol += 1
    species = data['atomic_numbers']
    coordinates = data['coordinates']
    wb97x_dz_dipole = data['wb97x_dz.dipole']
    wb97x_dz_cm5 = data['wb97x_dz.cm5_charges']
    wb97x_dz_hirshfeld = data['wb97x_dz.hirshfeld_charges']
    wb97x_dz_energy = data['wb97x_dz.energy']
    wb97x_dz_forces = data['wb97x_dz.forces']
    wb97x_tz_dipole = data['wb97x_tz.dipole']
    wb97x_tz_energy = data['wb97x_tz.energy']
    wb97x_tz_forces = data['wb97x_tz.forces']
    wb97x_tz_charges = data['wb97x_tz.mbis_charges']
    ccsdt_cbs_energy = data['ccsd(t)_cbs.energy']
    
    wb97x_dz_index = np.where(np.isfinite(wb97x_dz_dipole))
    wb97x_dz_index1 = np.unique(wb97x_dz_index[0])
    wb97x_dz_coordinates = coordinates[wb97x_dz_index1, :, :]
    wb97x_dz_dipole = wb97x_dz_dipole[wb97x_dz_index1, :]
    wb97x_dz_cm5 = wb97x_dz_cm5[wb97x_dz_index1, :]
    wb97x_dz_hirshfeld = wb97x_dz_hirshfeld[wb97x_dz_index1, :]
    wb97x_dz_energy = wb97x_dz_energy[wb97x_dz_index1]
    wb97x_dz_forces = wb97x_dz_forces[wb97x_dz_index1, :, :]
    
    wb97x_tz_index = np.where(np.isfinite(wb97x_tz_dipole))
    wb97x_tz_index1 = np.unique(wb97x_tz_index[0])
    wb97x_tz_coordinates = coordinates[wb97x_tz_index1, :, :]
    wb97x_tz_dipole = wb97x_tz_dipole[wb97x_tz_index1, :]
    wb97x_tz_energy = wb97x_tz_energy[wb97x_tz_index1]
    wb97x_tz_forces = wb97x_tz_forces[wb97x_tz_index1, :, :]
    wb97x_tz_charges = wb97x_tz_charges[wb97x_tz_index1, :]
    
    ccsdt_cbs_index = np.where(np.isfinite(ccsdt_cbs_energy))
    ccsdt_cbs_coordinates = coordinates[ccsdt_cbs_index, :, :]
    ccsdt_cbs_energy = ccsdt_cbs_energy[ccsdt_cbs_index]

    dpack1.store_data(data['path'],
                      species = species,
                      coordinates = wb97x_dz_coordinates,
                      energies = wb97x_dz_energy,
                      dipoles = wb97x_dz_dipole,
                      forces = wb97x_dz_forces,
                      cm5 = wb97x_dz_cm5,
                      hirshfeld = wb97x_dz_hirshfeld,
                     )  

    dpack2.store_data(data['path'],
                      species = species,
                      coordinates = wb97x_tz_coordinates,
                      energies = wb97x_tz_energy,
                      dipoles = wb97x_tz_dipole,
                      forces = wb97x_tz_forces,
                      charges = wb97x_tz_charges,
                     )
    
    dpack3.store_data(data['path'],
                      species = species,
                      coordinates = ccsdt_cbs_coordinates,
                      energies = ccsdt_cbs_energy,
                     )
    
dpack1.cleanup()
dpack2.cleanup()
dpack3.cleanup()

In [20]:
dpack1.cleanup()
dpack2.cleanup()
dpack3.cleanup()

In [22]:
print(n_mol)

3114


In [23]:
import os
import numpy as np
import torchani
from torchani.data._pyanitools import anidataloader
from torchani.data._pyanitools import datapacker

mol_data = dict()
n_mol = 0
db = anidataloader('./ani1x-20191001_rz.h5')
dpack3 = datapacker('./ani1x-20191001_ccsdt_cbs.h5')

for i, data in enumerate(db):
    # print(data['path'])
    # print(data.keys())
    n_mol += 1
    species = data['atomic_numbers']
    coordinates = data['coordinates']
    ccsdt_cbs_energy = data['ccsd(t)_cbs.energy']
    
    ccsdt_cbs_index = np.where(np.isfinite(ccsdt_cbs_energy))
    ccsdt_cbs_index1 = np.unique(ccsdt_cbs_index[0])
    ccsdt_cbs_coordinates = coordinates[ccsdt_cbs_index1, :, :]
    ccsdt_cbs_energy = ccsdt_cbs_energy[ccsdt_cbs_index1]

    dpack3.store_data(data['path'],
                      species = species,
                      coordinates = ccsdt_cbs_coordinates,
                      energies = ccsdt_cbs_energy,
                     )
    
dpack3.cleanup()

In [24]:
print(n_mol)

3114


In [ ]:
import os
import numpy as np
import torchani
from torchani.data._pyanitools import anidataloader
from torchani.data._pyanitools import datapacker

mol_data = dict()
n_mol = 0
db = anidataloader('./ani1x-20191001_rz.h5')
db1 = anidataloader('./ani1x-20191001_wb97x_dz_dipole.h5')
db2 = anidataloader('./ani1x-20191001_wb97x_tz_dipole.h5')
db3 = anidataloader('./ani1x-20191001_ccsdt_cbs.h5')

for i, data in enumerate(db):


In [1]:
import os
import numpy as np
import torchani
from torchani.data._pyanitools import anidataloader
from torchani.data._pyanitools import datapacker

code = {"1" : "H", "2" : "He", "3" : "Li", "4" : "Be", "5" : "B", \
"6"  : "C", "7"  : "N", "8"  : "O",  "9" : "F", "10" : "Ne", \
"11" : "Na" , "12" : "Mg" , "13" : "Al" , "14" : "Si" , "15" : "P", \
"16" : "S"  , "17" : "Cl" , "18" : "Ar" , "19" : "K"  , "20" : "Ca", \
"21" : "Sc" , "22" : "Ti" , "23" : "V"  , "24" : "Cr" , "25" : "Mn", \
"26" : "Fe" , "27" : "Co" , "28" : "Ni" , "29" : "Cu" , "30" : "Zn", \
"31" : "Ga" , "32" : "Ge" , "33" : "As" , "34" : "Se" , "35" : "Br", \
"36" : "Kr" , "37" : "Rb" , "38" : "Sr" , "39" : "Y"  , "40" : "Zr", \
"41" : "Nb" , "42" : "Mo" , "43" : "Tc" , "44" : "Ru" , "45" : "Rh", \
"46" : "Pd" , "47" : "Ag" , "48" : "Cd" , "49" : "In" , "50" : "Sn", \
"51" : "Sb" , "52" : "Te" , "53" : "I"  , "54" : "Xe" , "55" : "Cs", \
"56" : "Ba" , "57" : "La" , "58" : "Ce" , "59" : "Pr" , "60" : "Nd", \
"61" : "Pm" , "62" : "Sm" , "63" : "Eu" , "64" : "Gd" , "65" : "Tb", \
"66" : "Dy" , "67" : "Ho" , "68" : "Er" , "69" : "Tm" , "70" : "Yb", \
"71" : "Lu" , "72" : "Hf" , "73" : "Ta" , "74" : "W"  , "75" : "Re", \
"76" : "Os" , "77" : "Ir" , "78" : "Pt" , "79" : "Au" , "80" : "Hg", \
"81" : "Tl" , "82" : "Pb" , "83" : "Bi" , "84" : "Po" , "85" : "At", \
"86" : "Rn" , "87" : "Fr" , "88" : "Ra" , "89" : "Ac" , "90" : "Th", \
"91" : "Pa" , "92" : "U"  , "93" : "Np" , "94" : "Pu" , "95" : "Am", \
"96" : "Cm" , "97" : "Bk" , "98" : "Cf" , "99" : "Es" ,"100" : "Fm", \
"101": "Md" ,"102" : "No" ,"103" : "Lr" ,"104" : "Rf" ,"105" : "Db", \
"106": "Sg" ,"107" : "Bh" ,"108" : "Hs" ,"109" : "Mt" ,"110" : "Ds", \
"111": "Rg" ,"112" : "Uub","113" : "Uut","114" : "Uuq","115" : "Uup", \
"116": "Uuh","117" : "Uus","118" : "Uuo"}

count = 0
for data in anidataloader('./ani1x-20191001_wb97x_dz_dipole.h5'):
    count += 1
    filename = 'ani1x_20191001_' + data['path'].split('/')[-1] + '.xyz'
    f_out = open(filename, 'w+')
    for i in range(len(data['coordinates'])):
        f_out.write('%d \n' % len(data['species']))
        f_out.write(' mol: %s conformer: %d \n' % (filename, i+1))
        for at, coords in zip(data['species'], data['coordinates'][i]):
            symbol = code.get(str(at), 'X')
            f_out.write('%-5s %10.5f %10.5f %10.5f\n' % (symbol, coords[0], coords[1], coords[2]))
    f_out.close()
    if count > 10:
        break
